
project_id = "twqcybbjyhcokcrdfgkk"

[functions.bitrix-events]
verify_jwt = false

[functions.bitrix-oauth-callback]
verify_jwt = false

[functions.bitrix-oauth-start]
verify_jwt = true

[functions.bitrix-openlines-manager]
verify_jwt = true

[functions.bitrix-openlines-webhook]
verify_jwt = false
